version: '3.5'
services:
  valorant-watcher:
    build: .
    image: valorant-watcher:latest
    restart: always
    env_file: .env
    environment:
      # - token=02rt1omad7ororp
      # - stream=gaules
      #- userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
      - browserScreenshot=true
      - headlessMode=true
      #- proxy=ip:port
      #- proxyAuth=username:password
    volumes:
     - "./screenshots:/usr/src/app/screenshots"
